#!/bin/bash

if [ $# -eq 0 ]; then
  echo "No argument supplied !"
  exit 0
fi

set -a
. configuration.txt
set +a

if [ $1 == "template" ]; then
	if [ -d "template" ]; then
		echo "The template folder already exist, run this script will remove it and any changes will be lost."
		echo "If you want to preserve your modifications, copy this folder elsewhere before run this script."
		read -p "Are you sure you want to remove the current template folder ? (yes/no)" -n 1 -r
		echo
		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
			exit 1
		fi
	fi

	rm -rf template

	cp -Rp template-config template

	perl -pe 's/{{(.*?)}}/$ENV{$1}/g' "template-config/build_support/GenerateConfig.groovy" > template/build_support/GenerateConfig.groovy
	perl -pe 's/{{(.*?)}}/$ENV{$1}/g' "template-config/build_support/shared.maven.filters" > template/build_support/shared.maven.filters
else
	perl -pe 's/{{(.*?)}}/$ENV{$1}/g' "docker-compose.yml.tpl" > docker-compose.yml

	docker-compose $@
fi
