#!/bin/bash

if [ $# -eq 0 ]; then
  echo "No argument supplied !"
  exit 0
fi

set -a
. configuration.txt
set +a

perl -pe 's/{{(.*?)}}/$ENV{$1}/g' "docker-compose.yml.tpl" > docker-compose.yml

docker-compose $@
